[[redirects]]
 from = '/*'
 to = '/index.html'
 status = 200
[[redirects]]
 from = '/api/*'
 to = 'https://word-data-database.herokuapp.com/api'
 force = true
 status = 200
 headers = {Access-Control-Allow-Origin = "*"}
[[headers]]
 for = "/*"
 [headers.values]
   Access-Control-Allow-Origin = "*"